kind: Service
apiVersion: v1
metadata:
  name: dodvehicle-service
  namespace: dod-test
  annotations:
   cloud.google.com/neg: '{"exposed_ports": {"80":{}}}'
  labels:
    app: vehicle-test
spec:
  type: ClusterIP
  selector:
    app: vehicle-test
  ports: 
  - port: 80
    targetPort: 7000
    protocol: TCP
